# Remote test FDP
# catalog_url: http://178.63.49.197:8051/catalog/d02af5a9-038f-44da-9447-0370fde9d9b4

# Local test FDP
catalog_url: http://localhost/catalog/cfe9176f-1753-45b8-bda9-a47a6d5d3037

# FDP template
dataset_file: "test-input/fff-datasets.csv"
distribution_file: "test-input/fff-distribution.csv"
# distribution_file: "test-input/fff-sa-distribution.csv"
semantic_artefact_file: "test-input/fff-semantic-artefact.csv"

# EJPRD template
# ejp_vp_file: vp_test_input/EJPRD_Resource_Metadata_template.xlsx

# Dry run?
dry_run: false